export enum ActionType {
  //LOGIN
  USER_AUTHORIZED = 'USER_AUTHORIZED',
  AUTH_CODE_OBTAINED = 'AUTH_CODE_OBTAINED',
  ACCESS_TOKEN_OBTAINED = 'ACCESS_TOKEN_OBTAINED',
  REFRESH_TOKEN_OBTAINED = 'REFRESH_TOKEN_OBTAINED',

  //USER DATA
  USER_TOP_DATA_OBTAINED = 'USER_TOP_DATA_OBTAINED',
  USER_INPUT_SELECTED = 'USER_INPUT_SELECTED',

  //UI
  TOGGLE_LOADING = 'TOGGLE_LOADING',
}